version: "3.1"

networks:
  monitor-net:
    driver: bridge

services:
  # Monitor host metrics
  nodeexporter:
    image: prom/node-exporter:v1.3.0
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
    expose:
      - 9100
    # network_mode: host
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    
  # Monitor container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - /cgroup:/cgroup:ro
    restart: always
    expose:
      - 8080
    # network_mode: host
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  # Retrieve log from hosts and containers
  promtail:
    image: grafana/promtail:2.6.0
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
      - ./loki/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: always
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  # Fake Logs
  log_agent:
    image: log_agent/log_agent:latest
    build:
      context: ./log-agent
      dockerfile: Dockerfile
    container_name: log_agent
    restart: always
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"